In [3]:
import pandas as pd

# Load your dataset
dataset = pd.read_csv("D:/Sx Varun/Sx Code/MCA/2nd_Tri/python/dataSet/employee_compensation.csv")
dataset1 = dataset

# Clean numeric columns – remove commas and convert to float
cols_to_clean = ['REGULAR', 'RETRO', 'OTHER', 'OVERTIME', 'TOTAL GROSS']
for col in cols_to_clean:
    dataset1[col] = (dataset1[col]
                     .astype(str)
                     .str.replace(",", "", regex=False)
                     .replace("", 0)
                     .astype(float))

dataset1.head()

,NAME,DEPARTMENT_NAME,TITLE,REGULAR,RETRO,OTHER,OVERTIME,INJURED,DETAIL,QUINN_EDUCATION,TOTAL GROSS,POSTAL
0,"Hallahan,Timothy J",Traffic Division,Supv-Parking Meter Operations,114623.09,NaN,NaN,125523.80,NaN,NaN,NaN,240146.89,1940.0
1,"Hesford,Edward D.",Traffic Division,Supvising Traffic Engineer,133169.08,NaN,NaN,94803.60,NaN,NaN,NaN,227972.68,2131.0
2,"Aleman,Wilson",Traffic Division,Asst Supv Traffic Eng,111273.88,2034.51,984.78,84396.91,NaN,NaN,NaN,198690.08,2191.0
3,"Bloom,David M",Finance,Chief Financial Officer(F),194429.06,NaN,NaN,NaN,NaN,NaN,NaN,194429.06,2132.0
4,"Vilar,Alfredo J.",Traffic Division,Sr Traffic Engineer,107792.88,1869.34,2153.71,70844.88,NaN,NaN,NaN,182660.81,2155.0

In [ ]:
# 1 Rows and Columns
dataset1.shape

(573, 12)

In [7]:
# 2 EMP1 – Employee Name, Department, Total Earnings
EMP1 = dataset1[['NAME', 'DEPARTMENT_NAME', 'TOTAL GROSS']]
EMP1.head()

                 NAME   DEPARTMENT_NAME  TOTAL GROSS
0  Hallahan,Timothy J  Traffic Division    240146.89
1   Hesford,Edward D.  Traffic Division    227972.68
2       Aleman,Wilson  Traffic Division    198690.08
3       Bloom,David M           Finance    194429.06
4    Vilar,Alfredo J.  Traffic Division    182660.81

In [8]:
# 3 EMP2 – all variables except Overtime
EMP2 = dataset1.drop(columns=['OVERTIME'])
EMP2.head()

,NAME,DEPARTMENT_NAME,TITLE,REGULAR,RETRO,OTHER,INJURED,DETAIL,QUINN_EDUCATION,TOTAL GROSS,POSTAL
0,"Hallahan,Timothy J",Traffic Division,Supv-Parking Meter Operations,114623.09,NaN,NaN,NaN,NaN,NaN,240146.89,1940.0
1,"Hesford,Edward D.",Traffic Division,Supvising Traffic Engineer,133169.08,NaN,NaN,NaN,NaN,NaN,227972.68,2131.0
2,"Aleman,Wilson",Traffic Division,Asst Supv Traffic Eng,111273.88,2034.51,984.78,NaN,NaN,NaN,198690.08,2191.0
3,"Bloom,David M",Finance,Chief Financial Officer(F),194429.06,NaN,NaN,NaN,NaN,NaN,194429.06,2132.0
4,"Vilar,Alfredo J.",Traffic Division,Sr Traffic Engineer,107792.88,1869.34,2153.71,NaN,NaN,NaN,182660.81,2155.0

In [ ]:
# 4 Employees with Total >100K and Overtime >5K
high_earners = dataset1[(dataset1['TOTAL GROSS'] > 100000) & (dataset1['OVERTIME'] > 5000)]
len(high_earners)

58

In [10]:
# 5 EMP3 – only Finance department employees
EMP3 = dataset1[dataset1['DEPARTMENT_NAME'] == 'Finance']
EMP3.head()

,NAME,DEPARTMENT_NAME,TITLE,REGULAR,RETRO,OTHER,OVERTIME,INJURED,DETAIL,QUINN_EDUCATION,TOTAL GROSS,POSTAL
3,"Bloom,David M",Finance,Chief Financial Officer(F),194429.06,NaN,NaN,NaN,NaN,NaN,NaN,194429.06,2132.0
16,"Macrae,Yvonne",Finance,Director (NonAcad) D,150143.76,NaN,1500.0,NaN,NaN,NaN,NaN,151643.76,2333.0
22,"Racanelli,James",Finance,Director (NonAcad) D,145479.62,NaN,NaN,NaN,NaN,NaN,NaN,145479.62,2474.0
25,"Beltre,Cynthia",Finance,Director (NonAcad) D,142536.72,NaN,NaN,NaN,NaN,NaN,NaN,142536.72,2119.0
26,"Dawkins,Blair Elizabeth",Finance,Deputy Chief Financial Off (E),141921.13,NaN,NaN,NaN,NaN,NaN,NaN,141921.13,2121.0

In [11]:
# 6 EMP4 – sort descending by Total Earnings
EMP4 = dataset1.sort_values(by='TOTAL GROSS', ascending=False)
EMP4.head(10)

,NAME,DEPARTMENT_NAME,TITLE,REGULAR,RETRO,OTHER,OVERTIME,INJURED,DETAIL,QUINN_EDUCATION,TOTAL GROSS,POSTAL
0,"Hallahan,Timothy J",Traffic Division,Supv-Parking Meter Operations,114623.09,NaN,NaN,125523.80,NaN,NaN,NaN,240146.89,1940.0
1,"Hesford,Edward D.",Traffic Division,Supvising Traffic Engineer,133169.08,NaN,NaN,94803.60,NaN,NaN,NaN,227972.68,2131.0
2,"Aleman,Wilson",Traffic Division,Asst Supv Traffic Eng,111273.88,2034.51,984.78,84396.91,NaN,NaN,NaN,198690.08,2191.0
3,"Bloom,David M",Finance,Chief Financial Officer(F),194429.06,NaN,NaN,NaN,NaN,NaN,NaN,194429.06,2132.0
4,"Vilar,Alfredo J.",Traffic Division,Sr Traffic Engineer,107792.88,1869.34,2153.71,70844.88,NaN,NaN,NaN,182660.81,2155.0
5,"Dimarzo,Dominic",Traffic Division,Traffic Signal Supv,43198.05,NaN,NaN,NaN,"1,30,294.92",NaN,NaN,173492.97,2128.0
6,"Smith,Joseph M",Traffic Division,Supv-Parking Enforcement,116182.87,NaN,4393.42,52403.89,NaN,NaN,NaN,172980.18,2128.0
7,"Gove,Nicholas S",Traffic Division,Deputy Chief,166461.50,NaN,NaN,NaN,NaN,NaN,NaN,166461.50,2129.0
8,"Richards,Jay J.",Traffic Division,Asst Supv-Parking Enforcement,90583.12,1626.31,300.00,72622.41,NaN,NaN,NaN,165131.84,2122.0
9,"D'Avolio,Kristen",Adult Education,Senior Director (BASAS 12B),158597.40,NaN,5000.00,NaN,NaN,NaN,NaN,163597.40,2128.0

In [12]:
# 7 Add Annual_Bonus column = 10% of Regular Earnings
EMP2['Annual_Bonus'] = EMP2['REGULAR'] * 0.10
EMP2.head()

,NAME,DEPARTMENT_NAME,TITLE,REGULAR,RETRO,OTHER,INJURED,DETAIL,QUINN_EDUCATION,TOTAL GROSS,POSTAL,Annual_Bonus
0,"Hallahan,Timothy J",Traffic Division,Supv-Parking Meter Operations,114623.09,NaN,NaN,NaN,NaN,NaN,240146.89,1940.0,11462.309
1,"Hesford,Edward D.",Traffic Division,Supvising Traffic Engineer,133169.08,NaN,NaN,NaN,NaN,NaN,227972.68,2131.0,13316.908
2,"Aleman,Wilson",Traffic Division,Asst Supv Traffic Eng,111273.88,2034.51,984.78,NaN,NaN,NaN,198690.08,2191.0,11127.388
3,"Bloom,David M",Finance,Chief Financial Officer(F),194429.06,NaN,NaN,NaN,NaN,NaN,194429.06,2132.0,19442.906
4,"Vilar,Alfredo J.",Traffic Division,Sr Traffic Engineer,107792.88,1869.34,2153.71,NaN,NaN,NaN,182660.81,2155.0,10779.288

In [13]:
# 8 Average Regular & Overtime – entire dataset and per department
# 8(i) Entire dataset
avg_entire = dataset1[['REGULAR', 'OVERTIME']].mean()
avg_entire

# 8(ii) By department
avg_by_dept = dataset1.groupby('DEPARTMENT_NAME')[['REGULAR', 'OVERTIME']].mean()
avg_by_dept

                          REGULAR      OVERTIME
DEPARTMENT_NAME
Adult Education      80336.594375           NaN
Athletics            15036.317723           NaN
Auditing Department  83934.880976   2595.312500
Finance              94123.588065           NaN
Traffic Division     55742.978122  13974.076038

In [14]:
# 9 Top 5 highest-paid employees
top5 = dataset1.nlargest(5, 'TOTAL GROSS')[['NAME', 'TOTAL GROSS']]
top5

                 NAME  TOTAL GROSS
0  Hallahan,Timothy J    240146.89
1   Hesford,Edward D.    227972.68
2       Aleman,Wilson    198690.08
3       Bloom,David M    194429.06
4    Vilar,Alfredo J.    182660.81

In [15]:
# 10 Lowest Total Earnings per department
lowest_per_dept = dataset1.loc[dataset1.groupby('DEPARTMENT_NAME')['TOTAL GROSS'].idxmin()][['DEPARTMENT_NAME', 'NAME', 'TOTAL GROSS']]
lowest_per_dept

         DEPARTMENT_NAME                   NAME  TOTAL GROSS
518      Adult Education       Nguyen,Kimvy Thi      4309.17
563            Athletics         Molle,Kimberly      1028.61
405  Auditing Department  Morrison,Titus Eugene     21399.94
572              Finance  Kennedy Sr.,Donald R.       112.50
571     Traffic Division          Floyd,Chloe L       128.60

In [16]:
# 11 Department with highest average Overtime
dept_highest_overtime = (dataset1.groupby('DEPARTMENT_NAME')['OVERTIME']
                         .mean()
                         .idxmax())
dept_highest_overtime

'Traffic Division'

In [17]:
# 12 Add Level column (Low/Medium/High) in EMP2
def level_category(x):
    if x < 50000:
        return 'Low'
    elif x < 100000:
        return 'Medium'
    else:
        return 'High'

EMP2['Level'] = dataset1['TOTAL GROSS'].apply(level_category)
EMP2.head()

,NAME,DEPARTMENT_NAME,TITLE,REGULAR,RETRO,OTHER,INJURED,DETAIL,QUINN_EDUCATION,TOTAL GROSS,POSTAL,Annual_Bonus,Level
0,"Hallahan,Timothy J",Traffic Division,Supv-Parking Meter Operations,114623.09,NaN,NaN,NaN,NaN,NaN,240146.89,1940.0,11462.309,High
1,"Hesford,Edward D.",Traffic Division,Supvising Traffic Engineer,133169.08,NaN,NaN,NaN,NaN,NaN,227972.68,2131.0,13316.908,High
2,"Aleman,Wilson",Traffic Division,Asst Supv Traffic Eng,111273.88,2034.51,984.78,NaN,NaN,NaN,198690.08,2191.0,11127.388,High
3,"Bloom,David M",Finance,Chief Financial Officer(F),194429.06,NaN,NaN,NaN,NaN,NaN,194429.06,2132.0,19442.906,High
4,"Vilar,Alfredo J.",Traffic Division,Sr Traffic Engineer,107792.88,1869.34,2153.71,NaN,NaN,NaN,182660.81,2155.0,10779.288,High